### ISSUE TITLE
Practica 1.Anel Lorely Gonzalez Gonzalez.1AS

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-A-Lorely-Z#2]
[Practica 1.pdf](https://github.com/user-attachments/files/17442661/Practica.1.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
